name: WAKATIME
on:
  scheduel:
    - cron: "30 18 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: update readme
    runs-on: ubuntu-latest
    steps:
      - use: anmol098/waka-readme-stats
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: false
        
